---
- name: Preparazione pacchetti per compilazione RPM
  yum: pkg="{{ item }}" state=present
  with_items:
    - '@Development tools'
    - rpmdevtools
    - yum-utils
    - rpmlint
  become: yes

- name: Aggiungo utente per compilazione pacchetti RPM
  user:
    name: makepkg
    password: $6$rounds=100000$neTGJ5N7Nu5ogCTX$VmVgS9HRZcdczjiNNdQcZzFVQI/3AFwu6MNFOKxGhBRY4VcBOo6GTxhXr0K/jYVFTygjHWsr.teM6RmBzSnz.0
    shell: /bin/bash
    state: present
  become: yes

- name: Copia della chiave pubblica
  authorized_key: 
    user: makepkg
    key: "{{ lookup('file', '/Users/syntaxerrormmm/.ssh/id_rsa.pub') }}"
    state: present
  become: yes

- name: Creazione directory per il build di RPM
  shell: rpmdev-setuptree
  become: yes
  become_user: makepkg
