---

- name: Configure the edu-package following settings in domain.yml
  set_fact:
    edu_package: "{{ ansible_local.domain.edu_package }}"
  when: ansible_local.domain.edu_package is defined

- name: Verifica configurazione ibay preseed
  shell: /sbin/e-smith/db accounts show ks
  register: chk_ks_created
  changed_when: chk_ks_created.rc != 0
  ignore_errors: yes
  become: yes

- name: Configurazione web preseed
  shell: /sbin/e-smith/db accounts set ks ibay Description "Preseed share" GroupAccess rw HttpAccess private HttpAliasType default HttpAllowOverrideStatus disabled HttpForceSslStatus disabled HttpPasswordStatus disabled HttpStatus enabled HttpVirtualHost __ANY__ OtherAccess r OwningGroup locals SmbAuditStatus disabled SmbStatus disabled
  when: chk_ks_created|failed
  become: yes

- name: Attivazione web preseed
  shell: /sbin/e-smith/signal-event ibay-create ks
  when: chk_ks_created|failed
  become: yes

- name: Verifica presenza directory mirror
  file: path=/var/spool/apt-mirror/mirror state=directory
  register: chk_mirror_dir
  ignore_errors: yes
  become: yes

- name: Collegamento directory mirror
  file: path=/var/lib/nethserver/ibay/ks/mirror src=/var/spool/apt-mirror/mirror state=link
  become: yes
  when: chk_mirror_dir|success

- name: Creazione directory preseed
  file:
    path: "/var/lib/nethserver/ibay/ks/preseed"
    state: directory
  become: yes

- name: Copia profili preseed
  template:
    src: 'preseed/{{ item }}'
    dest: '/var/lib/nethserver/ibay/ks/preseed/{{ item }}'
  with_items:
    - edubuntu.seed
    - client-trusty.seed
    - docenti-trusty.seed
    - aula-trusty.seed
  become: yes

- block:
  - name: Creating development directory
    file:
      path: "/var/lib/nethserver/ibay/ks/preseed/dev"
      state: directory

  - name: Preseeding profiles - development
    template:
      src: 'preseed/dev/{{ item }}'
      dest: '/var/lib/nethserver/ibay/ks/preseed/dev/{{ item }}'
    with_items:
      - client-trusty.seed
      - docenti-trusty.seed
  when: development|bool
  become: yes

- name: Copia script post-installazione
  template:
    src: 'preseed/{{ item }}'
    dest: '/var/lib/nethserver/ibay/ks/preseed/{{ item }}'
  with_items:
    - postseed-client.sh
    - postseed-docenti.sh
    - postseed-aula.sh
    - pulseaudio-perms.sh
    - checksum.fact
  become: yes
